source "https://rubygems.org"
gem "lita"
gem "gerbilcharts"
# Uncomment to use the HipChat adapter
gem "lita-hipchat"
gem "lita-trisul"
gem "builder"
# Uncomment to use the IRC adapter
# gem "lita-irc"
gem "trisulrp"
# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
